"""empty message

Revision ID: 18a3f7d3ee05
Revises: ed25a6fb6acc
Create Date: 2019-05-19 22:33:49.915750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a3f7d3ee05'
down_revision = 'ed25a6fb6acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('statistic_id_uindex', table_name='statistic')
    op.create_unique_constraint(None, 'statistic', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'statistic', type_='unique')
    op.create_index('statistic_id_uindex', 'statistic', ['id'], unique=True)
    # ### end Alembic commands ###
