"""empty message

Revision ID: e148a3b0d875
Revises: 18a3f7d3ee05
Create Date: 2019-05-24 11:04:11.845099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e148a3b0d875'
down_revision = '18a3f7d3ee05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('categories_id_uindex', table_name='categories')
    op.drop_table('categories')
    op.drop_constraint('criterions_categories_id_fk', 'criterions', type_='foreignkey')
    op.drop_column('criterions', 'categories_id')
    op.drop_constraint('locations_subject_id_fk', 'locations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('locations_subject_id_fk', 'locations', 'subject', ['subject_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('criterions', sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('criterions_categories_id_fk', 'criterions', 'categories', ['categories_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pk')
    )
    op.create_index('categories_id_uindex', 'categories', ['id'], unique=True)
    # ### end Alembic commands ###
