"""empty message

Revision ID: ed25a6fb6acc
Revises: fbc2714ef7f8
Create Date: 2019-05-19 22:08:06.815577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed25a6fb6acc'
down_revision = 'fbc2714ef7f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('statistic', 'integer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('integer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('statistic', 'value')
    # ### end Alembic commands ###
